version: '3'
services:
  php:
    build: ./docker/php
    expose:
      - 9000
    volumes:
    #  - ./:/app
       - ./:/var/www/html
   # working_dir: /app
   # user: '1000:1000'
    # ports:
    #   - 8000:8000
    #command: php -S 0.0.0.0:8000 -t /app

  nginx:
    build: ./docker/server
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1